CREATE TABLE Pazienti (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Cod_fiscale CHAR(16) UNIQUE NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL,
    Data_Nascita DATE NOT NULL,
    Sesso CHAR(1) NOT NULL
);

CREATE TABLE Ospedali (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Indirizzo VARCHAR(255) NOT NULL
);

CREATE TABLE Diagnosi (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Data_Diagnosi DATE NOT NULL,
    ID_Paziente INTEGER NOT NULL,
    ID_Ospedale INTEGER NOT NULL,
    FOREIGN KEY (ID_Paziente) REFERENCES Pazienti(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ID_Ospedale) REFERENCES Ospedali(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Quesiti_Diagnostici (
    ID INTEGER PRIMARY KEY,
    Descrizione TEXT NOT NULL
);

CREATE TABLE Diagnosi_Quesiti (
    ID_Diagnosi INTEGER,
    ID_Quesito INTEGER,
    PRIMARY KEY (ID_Diagnosi, ID_Quesito),
    FOREIGN KEY (ID_Diagnosi) REFERENCES Diagnosi(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_Quesito) REFERENCES Quesiti_Diagnostici(ID) ON DELETE CASCADE
);

CREATE TABLE Amministratori (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Password CHAR(64) NOT NULL -- Cifrata in SHA256
);